### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by ttocs167** [ttocs167/Dice-Box#1]
- [ ] Roll multuple dice simultaneously
  - [x] System to select unique spawn points for each dice
  - [x] system to delay later rolls until spawn points are available
  - [ ] system to track all currently active rolls and trigger event when all rolls are complete
  - [ ] Disco flashing on max roll
- [ ] Textures for dice instead of current UI text and material colour

- [ ] Add UI
  - [x] Settings on UI and button to trigger roll with settings
  - [ ] Summary of the most recent roll, totals and separate
  - [ ] Lifetime data tracking to monitor fairness of dice

- [ ] Add other dice
  - [x] D2
  - [x] D4
  - [x] D6
  - [x] D8
  - [x] D10
  - [x] D12
  - [x] D20
  - [ ] D100

- [ ] New system for creating dice gameobject? Manual setup is tedious
